set arrow_color purple
# set auto_number
set rung_width 10
set rung_color blue
set line_color red

# not on Travis:
#set font "/Library/Fonts/Tahoma.ttf"

title that is that # test4
participant "Bob's JS" as Bob
participant Alice as Alice
Bob -> Alice: Test
Bob --> Alice: dash it all
Alice --> Bob: back dash
Bob ->> Alice: open
Alice ->> Bob: back open
Bob -->> Alice: Dash Open
Alice -->> Bob: dash back open
Bob -# Alice: miss LtoR
Bob --# Alice: dash miss LtoR
Alice -# Bob: miss RtoL
Alice --# Bob: dash miss RtoL
Bob -# Bob: Self-drop
Bob <-> Alice: <->
Bob <->> Alice: <->>
Bob <<-> Alice: <<->
Bob <<->> Alice: <<->>
Bob <--> Alice: <-->
Bob <-->> Alice: <-->>
Bob <<--> Alice: <<-->
Bob <<-->> Alice: <<-->>

loop outer
	loop first # with a comment
	end # also commented
	loop second
		loop inner
			loop inner inner
			end
		end
	end
	loop at least once
		loop lots of times
			here: Bob -> Alice: Test duration=2[duration=2]
			Alice@here ->> Bob: Another test duration=1 [duration=1]
			advance 1
			Bob->Alice
		end
		loop once
			Alice -> Bob [color=yellow]
		end
		loop twice
			Alice -> Bob: Hey!
		end
		loop three times a lady
			Alice -> Bob
		end
	end
end

opt Double arrows
	# This is a comment
	Bob <-> Alice: xxxy
	Bob -> Bob: This is a long label (TODO: wrap) [duration=2]
	Bob --> Bob: -->
	Bob ->> Bob: ->>
	Bob <-> Bob: <->
end

Bob->carlos
Bob<->carlos [duration=1]

# Lost packet
A -# B: Lost
A -# A: Lost self


# Notes
note Alice: Alice note
# This note will be right justified
note B: B note
